name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libglfw3 libglfw3-dev
      - name: Run configure script for release
        run: ./source/scripts/configure.sh release
      - name: Run build script for release
        run: ./source/scripts/build.sh release
      - name: Run test script for release
        run: ./source/scripts/test.sh release

  build-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libglfw3 libglfw3-dev
      - name: Run configure script for debug
        run: ./source/scripts/configure.sh debug
      - name: Run build script for debug
        run: ./source/scripts/build.sh debug
      - name: Run test script for debug
        run: ./source/scripts/test.sh debug

  build-windows-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio (vswhere)
        run: |
          $ErrorActionPreference = "Stop"
          $vs = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
          if ($vs) { Write-Host "Found Visual Studio at $vs" } else { Write-Host "Visual Studio not found" }

      - name: Install dependencies using vcpkg
        run: |
          C:/vcpkg/vcpkg update
          C:/vcpkg/vcpkg install glfw3

      - name: Configure CMake for release build
        run: |
          cmake -S . -B build/release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build the project (Release)
        run: |
          cmake --build build/release --config Release

      - name: Run tests (Release)
        run: |
          ctest --test-dir build/release --output-on-failure


